### ISSUE TITLE
checkinfiles.php - Needs to be checkInFiles (camelCase)

### ISSUE THREAD

**Issue by danielniemann** [jessgusclark/OmniAlexa#13]
The checkinfiles.php does not match the intent of checkInFiles. File name needs to be camelCase: checkInFiles

**Comment by jessgusclark** [comment]
So, I renamed it but GIT doesn't recognize it as being renamed since I think GIT is ignoring case. Would the best thing to do is to rename is something different, commit, then rename to camelCase? 

Damn Git!

**Comment by danielniemann** [comment]
Did you try a mv --force? See if it flags that the file already exists.

**Comment by jessgusclark** [comment]
I did not. 

Well shit, that looks like it might have worked.

**Comment by jessgusclark** [comment]
Resolved with #14
